// app/api/auth/[...nextauth]/route.ts

// This file simply exports the handlers generated by NextAuth.js
export { handlers as GET, handlers as POST } from "@/auth";

// Vercel Route Segment Config
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
